### ISSUE TITLE
Foundation Kit은 무엇이고 포함되어 있는 클래스들은 어떤 것이 있는지 설명하시오.

### ISSUE THREAD

**Issue by hyesuuou** [SwiftFrequency/iOSInterview#22]

**Comment by heerucan** [comment]
FoundationKit은 코코아 터치 프레임워크에 속해 있고 iOS앱을 만들기 위한 필수 프레임워크로
 기본 데이터 형식, 컬렉션 및 앱의 기본 객체와 기반 기술을 제공하는 역할이다.
주요 객체는 NSDate, NSData, NSURL, NSString, NSArray 등이 있다.

**Comment by Taehyeon-Kim** [comment]
Foundation Kit(Framework)는 Cocoa Touch Framework에 속해 있는 Framework이다. 원시 데이터 타입, 컬렉션 타입, 운영체제 서비스 등의 애플리케이션의 기본적인 기능을 관리하는 역할을 한다.

- NS 접두어가 붙은 객체를 사용하기 위해서는 Foundation을 import 해야 한다.
- Swift file을 생성할 때, 기본적으로 Foundation을 import 한채로 생성된다.
- Cocoa Touch Framework 내부에 속해 있는 UIKit은 내부적으로 Foundation을 import 하고 있다.

[정리 내용 참고]
https://taekki-ios-wiki.notion.site/Foundation-8875667253a943e1a571fa7a40a657f5

**Comment by hyesuuou** [comment]
Foundation Kit이란, iOS 개발 환경을 구축하기 위한 최상위 프레임워크인 Cocoa Touch Framework에 포함된 프레임워크로, 원시 데이터 타입, 컬렉션 타입 및 운영체제 서비스를 사용해 애플리케이션의 기본 기능을 관리하고, 데이터타입이나 날짜 및 시간, 필터 및 정렬, 네트워킹 등의 기본 기능을 제공한다.
## 1. 기본기능

- `Number` Data, String : 원시 데이터 타입 사용
- `Collection` Array, Dictionary, Set 등과 같은 컬렉션 타입 사용
- `Date and Time` 날짜와 시간을 계산하거나 비교하는 작업
- `Unit and Measurement` 물리적 자원을 숫자로 표현 및 관련 단위간 변환 기능
- `Data Formatting` 숫자, 날짜, 측정값 등을 문자열로 변환 또는 반대작업
- `Filter and Sorting` 컬렉션의 요소를 검사하거나 정렬하는 작업

## 2. 애플리케이션 지원

- `Resources` 애플리케이션의 에셋과 번들 데이터에 접근 지원
- `Notifiation` 정보를 퍼뜨리거나 받아들이는 기능 지원
- `App Extension` 확장 애플리케이션과의 상호작용 지원
- `Error and Exceptions` API와의 상호작용에서 발생할 수 있는 문제 상황에 대처할 수 있는 기능 지원

## 3. 파일 및 데이터 관리

- `File System` 파일 및 폴더를 생성하고 읽고 쓰는 기능 관리
- `Archives and Serialization` 속성목록, JSON, 바이너리 파일들을 객체로 변환 또는 반대 작업 관리
- `iCloud` 사용자의 iCloud 계정을 이용해 데이터를 동기화하는 작업 관리

## 4. 네트워킹

- `URL Loading System` 표준 프로토콜을 통해 URL과 상호작용하고 서버와 통신하는 작업
- `Bonjour` 로컬 네트워크를 위한 작업

**Comment by dlwns33** [comment]
Cocoa Touch Framework란 애플에서 제공하는 기본 프레임워크로, Foundation 프레임워크는 이 Cocoa Touch Framework에 포함되어있다. 
Foundation은 원시 데이터 타입(String, Int, Double), 컬렉션 타입(Array, Dictionary, Set) 및 운영체제 서비스를 사용해 애플리케이션의 기본적인 기능을 관리한다.

Viewcontroller를 생성하면 상단에 UIKit가 자동으로 추가되는데, UIKit만 있는데 원시 데이터 타입이나 컬렉션 타입이 사용 가능한 이유는 UIKit가 이미 Foundation을 import했기 때문이다.
